--
-- PostgreSQL database dump
--

\restrict XkA0JFhGfrdcwGduohpSqQxWfgI3omN1RrJ9kjmfojvMUzCS0b4p2TTZQzcT7QA

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-11-28 21:31:54

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 218 (class 1259 OID 17187)
-- Name: tb_filmes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_filmes (
    ano_lancamento integer,
    nota double precision,
    id bigint NOT NULL,
    usuario_id bigint,
    diretor character varying(255),
    titulo character varying(255)
);


ALTER TABLE public.tb_filmes OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 17186)
-- Name: tb_filmes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_filmes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_filmes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 17195)
-- Name: tb_usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tb_usuarios (
    id bigint NOT NULL,
    email character varying(255),
    login character varying(255),
    senha character varying(255),
    telefone character varying(255)
);


ALTER TABLE public.tb_usuarios OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17194)
-- Name: tb_usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tb_usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4853 (class 0 OID 17187)
-- Dependencies: 218
-- Data for Name: tb_filmes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_filmes (ano_lancamento, nota, id, usuario_id, diretor, titulo) FROM stdin;
2012	7.5	1	5	Peter Jackson	The Hobbit: An Unexpected Journey
2015	10	2	5	Nolan	Interestelar
1984	9	3	5	Não Lembro kkk	Rambo II: a missão
1978	10	4	6	George Lucas	Star Wars: a new hope
1984	10	6	6	George Lucas	Star Wars: The return of Jedi
1982	10	5	6	George Lucas	Star Wars: the Empire Strikes back
\.


--
-- TOC entry 4855 (class 0 OID 17195)
-- Dependencies: 220
-- Data for Name: tb_usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tb_usuarios (id, email, login, senha, telefone) FROM stdin;
4	teste@gmail.com	teste	$2a$10$T.Lale2pdmp7/kNso1435uKTVq4pFNygKmMDnxF8LA4Ze9JE6AbBa	17996800510
5	adrianohh58@gmail.com	Adriano Souza	$2a$10$gE8FFj.Uw5Vr5sdBd1/cAOnMYsl.jGaKBSNuNJDIrzYmBhUXPwxeW	17996800508
6	jorge@jorge.com	jorge	$2a$10$vo9vBssj3SVW4mevTkB6yubVCR8J3D/oS9qjX.hwzMWUunk80if4q	(17)987653455
\.


--
-- TOC entry 4861 (class 0 OID 0)
-- Dependencies: 217
-- Name: tb_filmes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_filmes_id_seq', 6, true);


--
-- TOC entry 4862 (class 0 OID 0)
-- Dependencies: 219
-- Name: tb_usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tb_usuarios_id_seq', 6, true);


--
-- TOC entry 4701 (class 2606 OID 17193)
-- Name: tb_filmes tb_filmes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_filmes
    ADD CONSTRAINT tb_filmes_pkey PRIMARY KEY (id);


--
-- TOC entry 4703 (class 2606 OID 17203)
-- Name: tb_usuarios tb_usuarios_login_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_usuarios
    ADD CONSTRAINT tb_usuarios_login_key UNIQUE (login);


--
-- TOC entry 4705 (class 2606 OID 17201)
-- Name: tb_usuarios tb_usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_usuarios
    ADD CONSTRAINT tb_usuarios_pkey PRIMARY KEY (id);


--
-- TOC entry 4706 (class 2606 OID 17204)
-- Name: tb_filmes fkbngh8mgha58gv8964suqngk74; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tb_filmes
    ADD CONSTRAINT fkbngh8mgha58gv8964suqngk74 FOREIGN KEY (usuario_id) REFERENCES public.tb_usuarios(id);


-- Completed on 2025-11-28 21:31:54

--
-- PostgreSQL database dump complete
--

\unrestrict XkA0JFhGfrdcwGduohpSqQxWfgI3omN1RrJ9kjmfojvMUzCS0b4p2TTZQzcT7QA

